export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const GET_TICKET_LOCATION = "GET_TICKET_LOCATION";
export const GET_TICKET_CATEGORY = "GET_TICKET_CATEGORY";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";

export const SET_RESPONSE = "SET_RESPONSE";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = "CREATE_PAYMENT_FAIL";
export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const GET_PAYMENT = "GET_PAYMENT";
export const GET_ORDER_BY_USER_ID = "GET_ORDER_BY_USER_ID";
