//We pass here different values without the need to rewrite it again, creation of reusable components
export const home0bjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Czech cuisine",
  headline: "Ready to discover the world of Czech cuisine?",
  description: "Get access to the Cooking recipes from original ingredients",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
export const home0bjTwo = {
  id: "explore",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Czech cuisine",
  headline: "Ready to discover the world of Czech cuisine?",
  description: "Get access to the Cooking recipes from original ingredients",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
